import{i as w,S as k,a as L}from"./assets/vendor-Br3gR3Vd.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))i(s);new MutationObserver(s=>{for(const n of s)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(s){const n={};return s.integrity&&(n.integrity=s.integrity),s.referrerPolicy&&(n.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?n.credentials="include":s.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(s){if(s.ep)return;s.ep=!0;const n=o(s);fetch(s.href,n)}})();const m={method:"POST",headers:{"Content-Type":"application/json",accept:"application/json"}},S=async e=>{m.body=JSON.stringify(e);try{const t=await fetch("https:portfolio-js.b.goit.study/api/requests",m);if(!t.ok)throw new Error(t.status);return t.json()}catch(t){throw console.log(t),t}},E=(e,t)=>{let o;return function(...i){clearTimeout(o),o=setTimeout(()=>e.apply(this,i),t)}},q=e=>w.warning({message:e,position:"topRight",backgroundColor:"#e74a3b",messageColor:"#FAFAFB",messageLineHeight:"24px",maxWidth:"310px",theme:"dark"}),j=(e,t,o)=>{const i=`
  <div class="modal">
    <button class="modal-btn-close" data-modal-close>
      <svg class="modal-close" width="24" height="24">
        <use href="./img/sprite.svg#close-modal"></use>
      </svg>
    </button>
    <h3 class="modal-title">${t}</h3>
    <p class="modal-text">
      ${o}
    </p>
  </div>`;e.innerHTML=i},r={contactForm:document.querySelector(".contact-form"),backDrop:document.querySelector(".backdrop"),errorMessage:document.querySelector(".notvalid"),checkedIcon:document.querySelector(".input-icon")},l=()=>r.backDrop.classList.toggle("is-hidden"),J=()=>{const e=document.querySelector("[data-modal-close]");l();const t=o=>{(o.code==="Escape"||o.currentTarget===o.target)&&(l(),window.removeEventListener("keydown",t))};window.addEventListener("keydown",t),r.backDrop.addEventListener("click",t),e.addEventListener("click",l)},M=e=>{e.preventDefault();const{email:{value:t},comment:{value:o}}=e.target;S({email:t,comment:o}).then(({title:i,message:s})=>{j(r.backDrop,i,s),J(),e.target.reset(),r.checkedIcon.classList.add("is-hidden")}).catch(i=>{q(`Error: № ${i.message}. Please verify the information you provided and try again `)})},x=E(e=>{const{valid:t}=e.target.validity;t?(r.errorMessage.classList.add("is-hidden"),e.target.classList.remove("notvalid"),r.checkedIcon.classList.remove("is-hidden")):(r.errorMessage.classList.remove("is-hidden"),e.target.classList.add("notvalid"))},1e3);r.contactForm.email.addEventListener("blur",()=>{r.errorMessage.classList.add("is-hidden")});r.contactForm.email.addEventListener("input",x);r.contactForm.addEventListener("submit",M);document.addEventListener("DOMContentLoaded",()=>{const e=document.querySelectorAll(".question-box");e.forEach(o=>{o.addEventListener("click",()=>{const i=o.parentElement,s=i.querySelector(".answer");s.style.display=s.style.display==="block"?"none":"block",i.classList.toggle("open"),e.forEach(n=>{const c=n.parentElement;c!==i&&(c.classList.remove("open"),c.querySelector(".answer").style.display="none")})})});const t=document.querySelector(".question-element");if(t){const o=t.querySelector(".answer");o.style.display="block",t.classList.add("open")}});const g={projectsList:document.querySelector(".projects-list")},v=[{title:"power pulse webservice",stacks:"React, JavaScript, Node JS, Git",link:"#"},{title:"mimino website",stacks:"React, JavaScript, Node JS, Git",link:"#"},{title:"vyshyvanka vibes Landing Page",stacks:"React, JavaScript, Node JS, Git",link:"#"},{title:"green harvest online store",stacks:"React, JavaScript, Node JS, Git",link:"#"},{title:"wallet webservice ",stacks:"React, JavaScript, Node JS, Git",link:"#"},{title:"chego jewelry website",stacks:"React, JavaScript, Node JS, Git",link:"#"},{title:"energy flow webservice ",stacks:"React, JavaScript, Node JS, Git",link:"#"},{title:"fruitbox online store",stacks:"React, JavaScript, Node JS, Git",link:"#"},{title:"English excellence webservice ",stacks:"React, JavaScript, Node JS, Git",link:"#"},{title:"starlight studio landing page",stacks:"React, JavaScript, Node JS, Git",link:"#"}],N=()=>{let e=g.projectsList.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})},B=e=>{let o="";v.slice(e,e+3).map((i,s)=>{const n=s+e+1;o+=`<li class="projects-item">
      <img
        src="./img/pj-${n}-min.jpg"
        srcset="./img/pj-${n}-min.jpg 
        alt="project image"
        class="project-img"
      />
      <p class="project-stacks">${i.stacks}</p>
      <div class="projects-box">
        <h3 class="projects-title">${i.title}</h3>
        <a class="projects-link" href="${i.link}"
          >visit
          <svg class="contacts-icon" width="24" height="24">
            <use href="./img/sprite.svg#icon-visit-arrow"></use>
          </svg>
        </a>
      </div>
    </li>`}),g.projectsList.insertAdjacentHTML("beforeend",o)},R={loadBtn:document.querySelector("#load-more")};let d=3;const $=e=>{if(B(d),N(),d+=3,d>v.length){e.target.classList.add("is-hidden");return}};R.loadBtn.addEventListener("click",$);const h=document.getElementById("theme-toggle"),u=document.body,P=(e,t)=>localStorage.getItem("theme")==="dark"&&e.classList.add(t),I=()=>{h.classList.toggle("active-btn"),u.classList.toggle("dark-theme"),u.classList.contains("dark-theme")?localStorage.setItem("theme","dark"):localStorage.setItem("theme","light")};P(u,"dark-theme");h.addEventListener("click",I);const a=new k(".swiper",{direction:"horizontal",navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},keyboard:{enabled:!0,onlyInViewport:!1},mousewheel:!0,slidesPerView:1,spaceBetween:20,breakpoints:{1280:{slidesPerView:2,spaceBetween:32}},on:{init:function(){this.isBeginning&&(document.querySelector(".swiper-button-prev").classList.add("button-disabled"),document.querySelector(".swiper-button-next").classList.remove("button-disabled"))},fromEdge:function(){document.querySelector(".swiper-button-next").classList.remove("button-disabled"),document.querySelector(".swiper-button-prev").classList.remove("button-disabled")},reachEnd:function(){document.querySelector(".swiper-button-next").classList.add("button-disabled")},reachBeginning:function(){document.querySelector(".swiper-button-prev").classList.add("button-disabled")}}});async function A(){try{const e=await L.get("https://portfolio-js.b.goit.study/api/reviews");if(!e.status===200)throw new Error("Network response was not ok");return e.data}catch(e){document.getElementById("not-found").style.display="block",console.log("Error fetching reviews: "+e.message)}}async function C(e){const t=await A(),o=document.getElementById("reviews-list"),i=t.reduce((s,n)=>`${s}
      <div class="swiper-slide">
        <p class="review-text">${n.review}</p>
        <div class="review-autor">
          <img class="review-autor__photo" src="${n.avatar_url}"></img>
          <p class="review-autor__name">${n.author}</p>
        </div>
      </div>`,"");o.insertAdjacentHTML("beforeend",i),a.update(),document.querySelector(".swiper").addEventListener("keydown",s=>{s.code==="ArrowLeft"&&(console.log("Keydown code: "+s.code),a.slidePrev()),s.code==="ArrowRight"&&(console.log("Keydown code: "+s.code),a.slideNext())}),document.querySelector(".swiper-button-prev").addEventListener("click",s=>a.slidePrev()),document.querySelector(".swiper-button-next").addEventListener("click",s=>a.slideNext())}const G=document.querySelector(".menu-icon-btn"),T=document.querySelector(".header-modal-btn"),y=document.querySelector(".header-modal"),F=document.querySelectorAll(".modal-list-item a"),f=document.querySelector("body");G.addEventListener("click",O);T.addEventListener("click",b);F.forEach(e=>e.addEventListener("click",b));function O(){y.classList.toggle("is-visible"),f.classList.toggle("body-hidden")}function b(){y.classList.remove("is-visible"),f.classList.remove("body-hidden")}const p=document.querySelector(".dark-mode-btn");p.addEventListener("click",function(){p.classList.toggle("dark-mode-active"),document.body.classList.toggle("dark-mode")});C();
//# sourceMappingURL=index.js.map
