import{i as l}from"./assets/vendor-Bk3t6AMZ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const d={method:"POST",headers:{"Content-Type":"application/json",accept:"application/json"}},u=async t=>{d.body=JSON.stringify(t);try{const e=await fetch("https:portfolio-js.b.goit.study/api/requests",d);if(!e.ok)throw new Error(e.status);return e.json()}catch(e){throw console.log(e),e}},m=(t,e)=>{let s;return function(...c){clearTimeout(s),s=setTimeout(()=>t.apply(this,c),e)}},p=t=>l.warning({message:t,position:"topRight",backgroundColor:"#e74a3b",messageColor:"#FAFAFB",messageLineHeight:"24px",maxWidth:"310px",theme:"dark",timeout:2e5}),g=(t,e,s)=>{const c=`
  <div class="modal">
    <button class="modal-btn-close" data-modal-close>
      <svg class="modal-close" width="24" height="24">
        <use href="./img/sprite.svg#close-modal"></use>
      </svg>
    </button>
    <h3 class="modal-title">${e}</h3>
    <p class="modal-text">
      ${s}
    </p>
  </div>`;t.innerHTML=c},n={contactForm:document.querySelector(".contact-form"),backDrop:document.querySelector(".backdrop"),errorMessage:document.querySelector(".notvalid"),checkedIcon:document.querySelector(".input-icon")},a=()=>n.backDrop.classList.toggle("is-hidden"),f=()=>{const t=document.querySelector("[data-modal-close]");a();const e=s=>{(s.code==="Escape"||s.currentTarget===s.target)&&(a(),window.removeEventListener("keydown",e))};window.addEventListener("keydown",e),n.backDrop.addEventListener("click",e),t.addEventListener("click",a)},h=t=>{t.preventDefault();const{email:{value:e},comment:{value:s}}=t.target;u({email:e,comment:s}).then(({title:c,message:o})=>{g(n.backDrop,c,o),f(),t.target.reset(),n.checkedIcon.classList.add("is-hidden")}).catch(c=>{p(`Error: № ${c.message}. Please verify the information you provided and try again `)})},y=m(t=>{const{valid:e}=t.target.validity;e?(n.errorMessage.classList.add("is-hidden"),t.target.classList.remove("notvalid"),n.checkedIcon.classList.remove("is-hidden")):(n.errorMessage.classList.remove("is-hidden"),t.target.classList.add("notvalid"))},1e3);n.contactForm.email.addEventListener("blur",()=>{n.errorMessage.classList.add("is-hidden")});n.contactForm.email.addEventListener("input",y);n.contactForm.addEventListener("submit",h);
//# sourceMappingURL=index.js.map
